/**
 * packages/db/src/migrate.ts
 *
 * Drizzle migration runner — applies pending SQL migrations to the database.
 *
 * Run via: `npm run db:migrate` (which calls `tsx src/migrate.ts`)
 *
 * This script:
 *   1. Connects to PostgreSQL using DATABASE_URL (or POSTGRES_* env vars)
 *   2. Creates a `_drizzle_migrations` table if it doesn't exist
 *   3. Reads migration files from the `drizzle/` directory
 *   4. Applies any pending migrations in order
 *   5. Logs the result and exits
 */
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { resolve } from 'node:path';

async function main(): Promise<void> {
  // Resolve the database connection URL from environment.
  const connectionString =
    process.env.DATABASE_URL ??
    `postgresql://${process.env.POSTGRES_USER ?? 'caregiver'}:${process.env.POSTGRES_PASSWORD ?? 'caregiver_dev'}@${process.env.POSTGRES_HOST ?? 'localhost'}:${process.env.POSTGRES_PORT ?? '5432'}/${process.env.POSTGRES_DB ?? 'caregiver'}`;

  console.info('[db:migrate] Connecting to database...');

  // Create a dedicated client for migrations (separate from the app pool).
  const client = postgres(connectionString, { max: 1 });
  const db = drizzle(client);

  // Path to the migrations folder (generated by `drizzle-kit generate`).
  const migrationsFolder = resolve(process.cwd(), 'drizzle');

  console.info(`[db:migrate] Applying migrations from ${migrationsFolder}...`);

  try {
    await migrate(db, { migrationsFolder });
    console.info('[db:migrate] Migrations applied successfully.');
  } catch (error) {
    console.error('[db:migrate] Migration failed:', error);
    process.exitCode = 1;
  } finally {
    await client.end();
  }
}

// Run the migration.
void main();
