/**
 * packages/db/src/schema/index.ts
 *
 * Drizzle ORM schema — the single source of truth for the database structure.
 *
 * Organized by domain:
 *   1. Identity (users, roles, user_roles)
 *   2. Clinical (appointments, vitals/observations, fhir_resources)
 *   3. AI (ai_diagnoses)
 *   4. Operations (alerts, audit_log)
 *
 * All tables use UUID primary keys (generated by pgcrypto).
 * Timestamps are timestamptz (timezone-aware).
 *
 * This file re-exports all table definitions and also provides a `schema`
 * object that bundles all tables for use in Drizzle queries.
 */
import { pgTable, uuid, varchar, text, timestamp, boolean, integer, jsonb, pgEnum } from 'drizzle-orm/pg-core';

// ══════════════════════════════════════════════════════════════
// ENUMS
// ══════════════════════════════════════════════════════════════

/**
 * Role enum — mirrors the 10 roles from @caregiver/rbac.
 * Stored as a Postgres enum for referential integrity.
 */
export const roleEnum = pgEnum('user_role', [
  'admin',
  'doctor',
  'nurse',
  'patient',
  'radiologist',
  'pharmacist',
  'billing_specialist',
  'lab_tech',
  'auditor',
  'medical_director',
]);

/** Appointment status enum — mirrors FHIR R4 AppointmentStatus. */
export const appointmentStatusEnum = pgEnum('appointment_status', [
  'proposed',
  'booked',
  'arrived',
  'fulfilled',
  'cancelled',
  'noshow',
  'entered-in-error',
  'checked-in',
  'waitlist',
]);

/** Alert severity enum. */
export const alertSeverityEnum = pgEnum('alert_severity', ['info', 'warning', 'critical', 'emergency']);

/** AI diagnosis status enum. */
export const aiDiagnosisStatusEnum = pgEnum('ai_diagnosis_status', [
  'requested',
  'processing',
  'completed',
  'approved',
  'overridden',
  'failed',
]);

// ══════════════════════════════════════════════════════════════
// IDENTITY TABLES
// ══════════════════════════════════════════════════════════════

/**
 * Users table — all platform users (patients, practitioners, staff).
 * Each user has one primary role (stored in `role` column).
 * Multi-role support can be added via user_roles junction table.
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  role: roleEnum('role').notNull(),
  // FHIR Practitioner/Patient resource reference (optional).
  fhirResourceId: uuid('fhir_resource_id'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Refresh tokens table — for JWT refresh token rotation.
 * Each token is tied to a user and has an expiry.
 */
export const refreshTokens = pgTable('refresh_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  token: varchar('token', { length: 512 }).notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ══════════════════════════════════════════════════════════════
// CLINICAL TABLES
// ══════════════════════════════════════════════════════════════

/**
 * Appointments table — scheduling data.
 * Mirrors key fields from FHIR R4 Appointment resource.
 */
export const appointments = pgTable('appointments', {
  id: uuid('id').primaryKey().defaultRandom(),
  // FHIR resource ID (if synced from FHIR).
  fhirId: varchar('fhir_id', { length: 64 }),
  patientId: uuid('patient_id').references(() => users.id),
  practitionerId: uuid('practitioner_id').references(() => users.id),
  status: appointmentStatusEnum('status').notNull().default('booked'),
  start: timestamp('start', { withTimezone: true }).notNull(),
  end: timestamp('end', { withTimezone: true }).notNull(),
  reason: text('reason'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Vitals (observations) table — patient vital signs and measurements.
 * Mirrors key fields from FHIR R4 Observation resource.
 * Stored as structured columns for common vitals + JSONB for the full FHIR resource.
 */
export const vitals = pgTable('vitals', {
  id: uuid('id').primaryKey().defaultRandom(),
  fhirId: varchar('fhir_id', { length: 64 }),
  patientId: uuid('patient_id')
    .notNull()
    .references(() => users.id),
  recordedBy: uuid('recorded_by')
    .notNull()
    .references(() => users.id),
  // Common vitals as typed columns for fast querying.
  heartRate: integer('heart_rate'),
  systolicBp: integer('systolic_bp'),
  diastolicBp: integer('diastolic_bp'),
  temperature: integer('temperature'), // Stored as ×100 to preserve 1 decimal (e.g. 98.6 → 9860)
  oxygenSaturation: integer('oxygen_saturation'),
  respiratoryRate: integer('respiratory_rate'),
  // Full FHIR Observation resource (JSONB) for complete fidelity.
  fhirResource: jsonb('fhir_resource'),
  recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * FHIR resources table — generic storage for all FHIR resources.
 * The full FHIR JSON is stored in the `resource` JSONB column.
 * The `resource_type` column enables filtering by FHIR resource type.
 */
export const fhirResources = pgTable('fhir_resources', {
  id: uuid('id').primaryKey().defaultRandom(),
  // FHIR resource type (Patient, Observation, etc.).
  resourceType: varchar('resource_type', { length: 64 }).notNull(),
  // FHIR logical ID (the `id` field in the FHIR resource).
  fhirId: varchar('fhir_id', { length: 64 }).notNull().unique(),
  // Full FHIR resource as JSONB.
  resource: jsonb('resource').notNull(),
  // Validation status (validated, pending, invalid).
  validationStatus: varchar('validation_status', { length: 32 }).notNull().default('pending'),
  // Validation errors (if any).
  validationErrors: jsonb('validation_errors'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ══════════════════════════════════════════════════════════════
// AI TABLES
// ══════════════════════════════════════════════════════════════

/**
 * AI diagnoses table — records of AI-assisted diagnosis requests and results.
 * Each row tracks the full lifecycle: requested → processing → completed → approved/overridden.
 */
export const aiDiagnoses = pgTable('ai_diagnoses', {
  id: uuid('id').primaryKey().defaultRandom(),
  // The patient the diagnosis is for.
  patientId: uuid('patient_id')
    .notNull()
    .references(() => users.id),
  // The practitioner who requested the diagnosis.
  requestedBy: uuid('requested_by')
    .notNull()
    .references(() => users.id),
  // The practitioner who approved/overrode the diagnosis (if applicable).
  reviewedBy: uuid('reviewed_by').references(() => users.id),
  status: aiDiagnosisStatusEnum('status').notNull().default('requested'),
  // The input prompt/context sent to the LLM.
  inputContext: jsonb('input_context'),
  // The LLM's diagnosis output.
  diagnosis: text('diagnosis'),
  // Source references from RAG retrieval (ChromaDB document IDs).
  sourceReferences: jsonb('source_references'),
  // Reviewer's notes (when approving/overriding).
  reviewNotes: text('review_notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
});

// ══════════════════════════════════════════════════════════════
// OPERATIONS TABLES
// ══════════════════════════════════════════════════════════════

/**
 * Alerts table — real-time alerts dispatched to users.
 * Created by the notifications microservice when threshold breaches or
 * critical events occur.
 */
export const alerts = pgTable('alerts', {
  id: uuid('id').primaryKey().defaultRandom(),
  // The patient the alert is about.
  patientId: uuid('patient_id').references(() => users.id),
  // The type of alert (vital_threshold, critical_lab, appointment_reminder, etc.).
  alertType: varchar('alert_type', { length: 64 }).notNull(),
  severity: alertSeverityEnum('severity').notNull().default('info'),
  // Alert message (human-readable).
  message: text('message').notNull(),
  // Whether the alert has been acknowledged.
  acknowledged: boolean('acknowledged').notNull().default(false),
  acknowledgedBy: uuid('acknowledged_by').references(() => users.id),
  acknowledgedAt: timestamp('acknowledged_at', { withTimezone: true }),
  // Whether the alert was escalated.
  escalated: boolean('escalated').notNull().default(false),
  // Additional metadata (JSONB).
  metadata: jsonb('metadata'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Audit log table — append-only log of all state-changing actions.
 * Written to exclusively by the audit microservice.
 * NEVER updated or deleted — enforced at the DB level.
 */
export const auditLog = pgTable('audit_log', {
  id: uuid('id').primaryKey().defaultRandom(),
  // Who performed the action.
  userId: uuid('user_id').references(() => users.id),
  userRole: roleEnum('user_role'),
  // What action was performed (create, read, update, delete, login, etc.).
  action: varchar('action', { length: 64 }).notNull(),
  // Which resource was affected (FHIR resource type + ID).
  resourceType: varchar('resource_type', { length: 64 }),
  resourceId: varchar('resource_id', { length: 64 }),
  // Result of the action (success/failure).
  result: varchar('result', { length: 32 }).notNull().default('success'),
  // Error message (if failed).
  errorMessage: text('error_message'),
  // Source IP address.
  sourceIp: varchar('source_ip', { length: 45 }),
  // Service that emitted the event.
  serviceName: varchar('service_name', { length: 64 }).notNull(),
  // Additional details (JSONB).
  details: jsonb('details'),
  // When the event occurred (immutable).
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
});

// ══════════════════════════════════════════════════════════════
// SCHEMA BUNDLE
// ══════════════════════════════════════════════════════════════

/**
 * The complete schema object — all tables bundled for use in Drizzle queries.
 *
 * @example
 *   import { createDb, schema } from '@caregiver/db';
 *   const db = createDb();
 *   const allUsers = await db.select().from(schema.users);
 */
export const schema = {
  users,
  refreshTokens,
  appointments,
  vitals,
  fhirResources,
  aiDiagnoses,
  alerts,
  auditLog,
};

// Individual tables are already exported via `export const` above.
// The `schema` object bundles them all for use in Drizzle queries.
